### PR TITLE
FLUME-3173: Upgrade joda-time

### PR DESCRIPTION
**Pull request by mcsanady**
Unit tests are passing.
Found no suspicious change in [joda-time release doc.](http://www.joda.org/joda-time/changes-report.html)

### CODE REVIEW

**Comment by marcellhegedus** [comment]
I think we can go with the latest stable release (v.2.9.9) which has the current ([2017b](http://www.iana.org/time-zones)) tz information out of the box.

**Comment by mcsanady** [comment]
@marcellhegedus I upgraded to v 2.9.6, because you tested s3 authentication with this version. Could you test this with v2.9.9 too?

**Comment by marcellhegedus** [comment]
@mcsanady Right. Retested s3 authentication and it also works with joda-time-2.9.9.jar. Thanks for the patch! LGTM +1

**Comment by adenes** [comment]
Thank you @mcsanady for the patch and @marcellhegedus for the review, I'm about to commit this.

**Pull request closed without merging**
