### PR TITLE
Docs: add Impala and Hive recommendation on hdfs.writeFormat setting in user guide

### PR DESCRIPTION
**Pull request by simonati**
no jira exists for this request. please let me know if it is needed.

### CODE REVIEW

**Review by adenes — APPROVED** [review]
Thanks for this patch, looks good to me.

**Comment by jholoman** [comment]
LGTM, thanks for patch

**Review by jholoman — APPROVED** [review]

**Comment by bessbd** [comment]
I'm about to commit this

**Comment by bessbd** [comment]
@simonati : thank you for the patch!

**Comment by bessbd** [comment]
@adenes , @jholoman : thank you for the reviews!

**Pull request closed without merging**
