### PR TITLE
Fix KafkaSource and KafkaSink example configurations in the user guide

### PR DESCRIPTION
**Pull request by simonati**
I haven't created a jira for this. Please let me know if it is needed then I would be more than happy to create one.

### CODE REVIEW

**Review by jholoman — COMMENTED** [review]
LGTM. Thanks for catching this.

**Review by adenes — APPROVED** [review]
👍

**Comment by bessbd** [comment]
+1, LGTM

I'm about to commit this

**Comment by bessbd** [comment]
@satiatcloudera : thank you for the patch!

**Comment by bessbd** [comment]
@jholoman , @adenes : thank you for the reviews!

**Pull request closed without merging**
