### PR TITLE
Add Developer Section / How to Contribute from cwiki.apache.org

### PR DESCRIPTION
**Pull request by bessbd**

### CODE REVIEW

**Comment by bessbd** [comment]
In a separate commit, we should consider adding info about pull requests

**Review by simonati — COMMENTED** [review]
LGTM
I checked content, links, formatting. TOC is missing but seems like it is down to github https://github.com/isaacs/github/issues/215

**Comment by bessbd** [comment]
I'm about to commit this

**Comment by bessbd** [comment]
@satiatcloudera : thank you for the review!

**Pull request closed without merging**
