### PR TITLE
FLUME-3051:Mention the incompatibility of Kafka source with 0.8.x Kafka brokers

### PR DESCRIPTION
**Pull request by umesh9794**
Please review

### CODE REVIEW

**Review by simonati — CHANGES_REQUESTED** [review]
Could you please synchronise this message amongst Kafka source/channel/sink?

**Comment by umesh9794** [comment]
Thanks @simonati. Will update the PR soon with synchronized messages amongst Kafka source/channel/sink.

**Comment by umesh9794** [comment]
@simonati, I have made the suggested changes. Please let me know your thoughts.

**Review by simonati — COMMENTED** [review]
The wording looks good. I would require a second opinion on the content. ie 1.7.x flume vs 0.8.x kafka.

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by szaboferee** [comment]
@umesh9794 thankyou for the PR, this issue was resolved by the #235 PR so it can be closed

**Pull request closed without merging**
