### PR TITLE
FLUME-2817. Sink for multi-agent flow example in user guide is set up incorrectly

### PR DESCRIPTION
**Pull request by marcellhegedus**

### CODE REVIEW

**Review by adenes — APPROVED** [review]
Thanks for the patch @marcellhegedus, it looks good to me, 👍

**Comment by marcellhegedus** [comment]
Thanks @adenes for the review! @bessbd please merge if you agree.

**Comment by bessbd** [comment]
LGTM, +1

I'm about to commit this

**Comment by bessbd** [comment]
@adenes : thank you for the review!

**Comment by bessbd** [comment]
@marcellhegedus : thank you for the patch!

**Pull request closed without merging**
