### PR TITLE
FLUME-3338: Add doc about Kafka channel recoverability

### PR DESCRIPTION
**Pull request by annamariakeppler**

### CODE REVIEW

**Review by bessbd — APPROVED** [review]
Lgtm, +1

**Review by szaboferee — APPROVED** [review]
+1

**Comment by bessbd** [comment]
I'm about to commit this.

**Comment by bessbd** [comment]
@annamariakeppler : thank you for the patch!

**Comment by bessbd** [comment]
@szaboferee : thank you for the review!

**Comment by belugabehr** [comment]
Thank you for completing my ticket. :)

**Pull request merged**
