### PR TITLE
FLUME-3216.Avoid reading content repeatedly.

### PR DESCRIPTION
**Pull request by highfei2011**
When I use Taildir source, whenever I rename a file, it causes flume to read the data repeatedly.This resulted in duplication of uploaded data.

### CODE REVIEW

**Comment by highfei2011** [comment]
When we moved the same file to another directory, and then moved back, making flume does not read the contents of the file repeatedly.

**Comment by dlanza1** [comment]
+1

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by highfei2011** [comment]
Closed this pull.

**Comment by cjd0831** [comment]
> Closed this pull.

I'm seeing this too. 
Why is it closed?

**Pull request closed without merging**
