### PR TITLE
WIP: Fix PMD violations in Thrift source

### PR DESCRIPTION
**Pull request by AndreLouisCaron**
The affected files seem to be generated by the Thrift compiler.
Assuming there is a more recent version of the Thrift compiler that
emits code that passes the PMD checks, the proper thing to do would be
to upgrade.

I'm not familiar enough with the Java ecosystem and this project's CI to
perform that kind of expiriment at this time.  I'm just trying to fix
the CI build in order to make other changes, so please be lenient :-)

### CODE REVIEW

**Comment by mpercy** [comment]
These are generated files and should not be manually edited. If you want to stop the warnings, better to prevent SpotBugs from running on these generated files. I'm not sure how to do it but suspect it should be controllable via the Maven build.

**Comment by mpercy** [comment]
err, PMD

**Comment by AndreLouisCaron** [comment]
Yeah, I figured as much, but:

1) I have no idea what I'm doing;
2) I have very limited time to spend on this; and
3) I wasn't 100% sure this would even fix the build yet.

Now that we see the build passing, I'll mark this as WIP and see if I can exclude the files from the PMD checks.

**Comment by AndreLouisCaron** [comment]
After fiddling around with the PMD plug-in exclusion configuration for over 2 hours, I cannot get it to ignore violations by file and I cannot get it to ignore violations from inner classes (those with a `$` in them).

I did manage to combine a mix of some exclusions and tweaking the threshold, which seems to fix the build.

See #325.

I can ditch this PR if you like the other one better.  Let me know what you think.

**Comment by AndreLouisCaron** [comment]
Closing in favor of #325.

**Pull request closed without merging**
