### PR TITLE
Kudu Sink for Flume

### PR DESCRIPTION
**Pull request by arae**
https://issues.cloudera.org/browse/KUDU-431

### CODE REVIEW

**Comment by toddlipcon** [comment]
Hi Ara. Thanks for contributing this!

I haven't taken a look at the code quite yet, but one quick thought: would it be best to have this code hosted in the Flume project or in the Kudu project? I can think of a couple pros/cons:

Pros for contributing as part of the Flume repo:
- I think this is the "standard" -- eg the flume repo already has sinks for many other systems like elastic search, hbase, kafka, etc. So, seems like it would make sense to put Kudu in there as well.
- Flume users will have more of a "batteries included" experience -- no need to muck with classpaths or move jars into place, etc, to write to Kudu.

Pros for hosting as part of the Kudu repo:
- It's likely that, since Flume is a relatively stable/mature project, its APIs aren't going to break. Kudu is still in beta with new APIs and capabilities being added reasonably rapidly. Versioning the flume sink inside the Kudu repo will make it easier to (a) ensure that Kudu changes don't break the flume sink, and (b) quickly evolve the Flume sink to take advantage of those new features.
- Currently, the Kudu project doesn't export any "minicluster" JAR for use by external projects. So, it will be impossible to do any integration testing of the Kudu sink if it's part of the Flume project. On the other hand, if we include it in the Kudu repo, we already have build/test infrastructure that runs a local minicluster and we could easily write some simple integration tests.

Any thoughts on this? Would also like to solicit thoughts from the rest of the Flume community as well. Thanks.

**Comment by arae** [comment]
Hi Todd.

I’ll contact the Kudu guys and see what their preference is. Perhaps for now Kudu repos would be a better place for hosting these? Because Kudu is at v0.6 and not yet stable in many way.

Ara.

**Comment by toddlipcon** [comment]
Hey Ara. I am one of the Kudu guys :) Let's see what the Flume guys think, though.

**Comment by arae** [comment]
Oh ok :)

Ara.

**Comment by jarcec** [comment]
Considering the fact that Kudu is a new component that is still evolving, changing quite rapidly and is on much faster release schedule then flume, I would not mind having the Kudu sink part of kudu repository for the time being.

(I'm a Flume PMC member, but I'm representing my own opinion here)

**Comment by harishreedharan** [comment]
Until Kudu's APIs are stable and mature, I agree that having it in the Kudu project is probably a good idea. I would be really glad to have it in Flume once Kudu APIs are final and stable (and if testing would be easy).

**Comment by mpercy** [comment]
Hi @arae I'm a committer on both projects and I agree with @toddlipcon, @jarcec and @harishreedharan that this would be good to have as part of Kudu, at least for now. That would also allow us to test it using the MiniCluster. Right now Kudu doesn't ship MiniCluster binaries in a way that is downloadable via Maven (although I believ the java classes for the MiniCluster are be available via Maven). Would you mind squashing your PR into one commit and submitting a Gerrit CR to Kudu? Instructions are here: http://getkudu.io/docs/contributing.html

**Comment by arae** [comment]
Sure.

Ara.

**Comment by arae** [comment]
Done.

http://gerrit.cloudera.org:8080/2383

Ara.

On Mar 1, 2016, at 3:52 AM, Mike Percy <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi @araehttps://github.com/arae I'm a committer on both projects and I agree with @toddlipconhttps://github.com/toddlipcon and @jarcechttps://github.com/jarcec that this would be good to have as part of Kudu for now. That would also allow us to test it using the MiniCluster. Right now Kudu doesn't ship MiniCluster binaries in a way that is downloadable via Maven (although I believ the java classes for the MiniCluster are be available via Maven). Would you mind squashing your PR into one commit and submitting a Gerrit CR to Kudu? Instructions are here: http://getkudu.io/docs/contributing.html

—
Reply to this email directly or view it on GitHubhttps://github.com/apache/flume/pull/36#issuecomment-190686416.

---

This message is for the designated recipient only and may contain privileged, proprietary, or otherwise confidential information. If you have received it in error, please notify the sender immediately and delete the original. Any other use of the e-mail by you is prohibited. Thank you in advance for your cooperation.

---

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by szaboferee** [comment]
@arae as this pull request is already done. Could you please close it?

**Pull request closed without merging**
