### PR TITLE
[FLUME-3352]:Unnecessary canary test will block on readonly spooldir …

### PR DESCRIPTION
**Pull request by hackty**
related issue [https://issues.apache.org/jira/projects/FLUME/issues/FLUME-3352](url)

### CODE REVIEW

**Comment by hackty** [comment]
Can you please review? @bessbd @mpercy

**Comment by hackty** [comment]
Could you please review? @bessbd @mpercy

**Comment by bessbd** [comment]
Hi @hackty !

Thank you for this patch! On a first read, it looks good. Can you please add a test to ensure it works correctly and to avoid future changes accidentally removing this fix?

**Comment by hackty** [comment]
@bessbd Thanks for your prompt reply. Two unit tests were added to ensure the correctness on the fix.

The description of two unit test:
**testRenameTrackingPolicyOnReadonlySpoolDirectory**
One supplemented to examine the mechanisation of canary (RenameTrackingPolicy is enabled so the spooldir should have the write access.)
It can pass no matter before or after the fix.

**testTrackerDirTrackingPolicyOnReadonlySpoolDirectory**
One that added to ensure the correctness on currect fix.(TrackerDirTrackingPolicy is enabled and the trackdir is different from spooldir. This time the write permission of spooldir is not necessary to the trackdir and also works well.)
It can fail before the fix and pass after the fix.

**Comment by hackty** [comment]
Could you please review the tests? @bessbd

**Comment by bessbd** [comment]
Thank you for the tests and the descriptions, @hackty .
It looks good to me. I'll leave some time for @mpercy to add his comments.

**Comment by mpercy** [comment]
Patch looks good to me, tests pass. Thanks for the contribution and your patience and persistence in getting this reviewed, @hackty!

**Review by mpercy — APPROVED** [review]

**Pull request merged**
