### PR TITLE
FLUME-3031: sequence source should reset its counter for event body on channel exception

### PR DESCRIPTION
**Pull request by simonati**
added code fix for event body generation
updated user guide
reworked testing: removed original tests and introduced three new one to extend coverage

### CODE REVIEW

**Comment by simonati** [comment]
Patch contains code fix, user guide update and testing. The diff for test looks ugly because it is full rework of tests (removed the original ones as they are covered by the new ones also the original tests didn't cover rollback).

Tests pass: (the new tests failed before the code fix)
mvn test -Dtest=org.apache.flume.source.TestSequenceGeneratorSource -pl flume-ng-core

**Comment by simonati** [comment]
mvn site -DskipTests passes on my local branch not including latest commit.
Please note that site on trunk is broken. Fix for that is https://github.com/apache/flume/pull/91

**Review by adenes — APPROVED** [review]
Thanks for the fix, 👍

**Comment by simonati** [comment]
Thanks @adenes for the review!
@jholoman, @bessbd could you please do a final review? Thanks.

**Review by jholoman — APPROVED** [review]
LGTM

**Comment by adenes** [comment]
@bessbd, @jholoman could you please commit this? (Unless there is any objection, of course). Thanks.

**Comment by bessbd** [comment]
LGTM, +1

**Comment by bessbd** [comment]
I'm about to commit this

**Comment by bessbd** [comment]
@simonati : thank you for the patch!

**Comment by bessbd** [comment]
@adenes , @jholoman : thank you for the reviews!

**Pull request closed without merging**
