### PR TITLE
FLUME-3132 Upgrade tomcat jasper library dependencies

### PR DESCRIPTION
**Pull request by szaboferee**
excluding vulnerable dependencies

### CODE REVIEW

**Review by mcsanady — APPROVED** [review]
Looks good to me.

**Review by simonati — COMMENTED** [review]
With this change Jasper will be only a test scope dependency which is better than what we have now. 

Is jasper really needed to run our tests?

**Comment by szaboferee** [comment]
In my understanding Jasper is not needed anywhere, however it is a transitive dependency from hadoop   and hadoop is a dependency in some test cases

**Comment by simonati** [comment]
If it is not needed for our tests then do you think it is worth excluding it from the test scope as well?

**Comment by szaboferee** [comment]
I removed it from the test scope as well.
the new dependency diff is:
```
71d70
< [INFO]    commons-el:commons-el:jar:1.0:compile
532,536d530
< [INFO]    tomcat:jasper-compiler:jar:5.5.23:runtime
< [INFO]    tomcat:jasper-compiler:jar:5.5.23:test
< [INFO]    tomcat:jasper-runtime:jar:5.5.23:compile
< [INFO]    tomcat:jasper-runtime:jar:5.5.23:runtime
< [INFO]    tomcat:jasper-runtime:jar:5.5.23:test
```

The build with tests was successful

**Review by simonati — APPROVED** [review]
LGTM

**Pull request closed without merging**
