### PR TITLE
ability to override any parameter from the configuration file via the -o /

### PR DESCRIPTION
**Pull request by keyki**
-override parameter

### CODE REVIEW

**Comment by keyki** [comment]
We are planning to start flume agents dynamically and it comes handy to be able to override parameters of a base configuration file without actually touching and modifying it, for example change the bind port.  

Example:  

agent.sources.avro-collection-source.bind = localhost
agent.sources.avro-collection-source.port = 50000
agent.sinks.hdfs-sink.hdfs.path = hdfs://localhost:9000/flume
agent.channels.memoryChannel.capacity = 20000

flume-ng agent -n agent -f flume.conf 
-o avro-collection-source.bind=0.0.0.0 
-o avro-collection-source.port=30000
-o hdfs-sink.hdfs.path=hdfs://localhost:9000/data
-o memoryChannel.capacity=30000

**Comment by jarcec** [comment]
Hi Krisztian,
would you mind opening a new Flume JIRA and submitting your patch there? Due to the formalities and different licences we can't accept pull requests from Github.

http://issues.apache.org/jira/browse/FLUME

Jarcec

**Comment by keyki** [comment]
Hi Jarcec,

Here is the link, https://issues.apache.org/jira/browse/FLUME-2351

**Comment by jarcec** [comment]
Thank you Krisztian, The flume folks should be able to look into it shortly!

Jarcec

**Pull request closed without merging**
